language: php
sudo: true
php:
  - '7.1'
  - '7.2'
  - '7.3'
before_install: echo "extension = curl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - travis_retry composer install --prefer-dist --no-interaction
script:
  - composer test